// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ogolznrwwkxvaybyajim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9nb2x6bnJ3d2t4dmF5YnlhamltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNDkxMDAsImV4cCI6MjA2MzcyNTEwMH0.ZO18xGzFSdd9_hffje5O-dwM9QWCHN85ZGCvv5oWeFc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);